### ISSUE TITLE
Scripts not working

### ISSUE THREAD

**Issue by rohitme89** [neerajsinghsonu/Instagram-Data-Scraper#1]
Please check this script nothing is working

**Comment by neerajsinghsonu** [comment]
Hi @rohitme89 , The script is working fine, I just `downloaded the file zip` from repo and extract and paste inside my `"D:\wamp\www\Instagram-Data-Scraper-master"` folder. Then I just `rename dev.htaccess` to `.htaccess` and checked url with browser` "http://localhost/Instagram-Data-Scraper-master/?dummy=1"` and everything working perfectly! 

I am assuming it's not application/script problem it's `re_write` module problem in your` WAMP/XAMP`,  Make sure you have enabled `re_write module` in `apache`.

Thanks :)

**Comment by rohitme89** [comment]
This script is not working my online link.
working on local server such as wamp and xamp.

**Comment by neerajsinghsonu** [comment]
@rohitme89, please make sure you have enabled mode re_write module on live server and also make sure your server support .htaccess rules. Let me know if you have any problem..

**Comment by neerajsinghsonu** [comment]
By the way.. I will post a very simple version of this script in 2 or 3 days, which require 0 configuration :| :-)

**Comment by gavyjatt** [comment]
The script still has issues

**Comment by neerajsinghsonu** [comment]
@gavyjatt Hi, Just committed new code. Please check once and let me know if it's work..
