### ISSUE TITLE
An error occurs if I search multibyte keyword on pull_hashtag

### ISSUE THREAD

**Issue by YuzuruS** [neerajsinghsonu/Instagram-Data-Scraper#10]
If I search multibyte keyword on pull_hashtag, An error occurs.

ex) #毛皮

![2018-01-31 0 09 48](https://user-images.githubusercontent.com/1485195/35573676-22baaa18-061b-11e8-87c1-24a02ddad47e.png)
![2018-01-31 0 10 06](https://user-images.githubusercontent.com/1485195/35573677-22fde58a-061b-11e8-965a-b9b7c4d08bdc.png)

**Comment by neerajsinghsonu** [comment]
Hi  YuzuruS,

I have tested with '#毛皮 #fur' & surprisingly it works for me.. If not then please try again... and please let me know if still no luck..

![screenshot-2018-1-31 instagram super scraper](https://user-images.githubusercontent.com/1378886/35584692-c93a69e6-061b-11e8-91ea-a42de3efcc88.png)

**Comment by YuzuruS** [comment]
@neerajsinghsonu 
I found error location.

https://github.com/neerajsinghsonu/Instagram-Data-Scraper/blob/master/includes/Instagram.php#L185

```
$this->curlResponseData = file_get_contents('https://www.instagram.com/explore/tags/毛皮/?__a=1');
```

if we use os without mac os, an error doesnt occur.
But we use mac os, an error occurs.

```
PHP Warning:  file_get_contents(https://www.instagram.com/explore/tags/毛皮/?__a=1): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway
```

This problem happens on Mac os + file_get_contents + multibyte char.

**Comment by YuzuruS** [comment]
I send PR !
