### ISSUE TITLE
if I searched multi byte tag name, I can see only single byte tag name on top posts keywords. 

### ISSUE THREAD

**Issue by YuzuruS** [neerajsinghsonu/Instagram-Data-Scraper#12]
if I searched multi byte tag name, I can see only single byte tag name on top posts keywords.

ex) #ベンチャー

```
1 | #tokyo | 56
2 | #web | 50
3 | #startup | 39
4 | #KK | 27
5 | #2019 | 26
6 | #TUKUDDO | 25
7 | #IT | 25
8 | #kagoshima | 24
9 | #19 | 22
10 | #japan | 21
11 | #design | 20
12 | #f4f | 20
13 | #sozo | 19
14 | #hackaton | 19
15 | #MA_2017 | 19
16 | #kyoto | 17
17 | #MA | 17
18 | #coding | 16
19 | #25 | 15
20 | #Lifes | 15
21 | #instagood | 14
22 | #MONO | 14
23 | #excel | 13
24 | #hackathon | 13
25 | #programming | 13
26 | #fashion | 13
27 | #creative | 13
28 | #startups | 13
29 | #imagine | 12
30 | #Wiz | 12
31 | #business | 12
32 | #webdesign | 12
33 | #app | 12
34 | #ceo | 12
35 | #mysozo | 12
36 | #fx | 11
37 | #lewagon | 10
38 | #2020 | 9
39 | #pdca | 9
40 | #vc | 9
41 | #lifestyle | 9
42 | #startuplife | 9
43 | #meo | 9
44 | #seo | 9
45 | #entrepreneur | 9
46 | #happy | 8
47 | #BLOCKS | 8
48 | #2018 | 8
49 | #fukuoka | 8
50 | #marketing | 8
```

![2018-02-03 12 32 13](https://user-images.githubusercontent.com/1485195/35762676-53cd06a8-08de-11e8-82ab-c817500fecf1.png)
![2018-02-03 12 32 23](https://user-images.githubusercontent.com/1485195/35762677-540212b2-08de-11e8-8620-8b453c27dc8d.png)

**Comment by neerajsinghsonu** [comment]
Hi @Yuzuru Suzuki,

This is the search keyword "ベンチャー" and what you are getting in Top Keywords Section that's all another hashtags within same #ベンチャー hashtag. A single hashtag post can have multiple another hashtags, that's what coming in that section.... with number of time they occurred in post.
