### ISSUE TITLE
Uncaught TypeError: Cannot read property 'user' of undefined

### ISSUE THREAD

**Issue by tahliakhenderson** [neerajsinghsonu/Instagram-Data-Scraper#16]
Hi, 

I am encountering an issue when I run the tool on a username (see screenshot) and the scrape does not complete or return any data. I do not have this issue when running the tool on a hash tag.

Any thoughts on how to fix this?

Note I have allow_url_fopen=on and openssl extension on.

Happy to hear any thoughts on this issue.

Thanks in advance.
Tahlia

![instascraperissue](https://user-images.githubusercontent.com/38149494/38463298-c88d48a2-3b3a-11e8-9de8-83395d192fed.jpg)

**Comment by neerajsinghsonu** [comment]
Hi Tahlia, Sorry for any inconvenience. We are looking into the issue and will fix soon.

**Comment by basharabdullah** [comment]
Thanks guys for this tool.

Wondering if there is a fix for this or not?

**Comment by neerajsinghsonu** [comment]
Hello @tahliakhenderson  & @basharabdullah 

User account has been fixed now :)
