### ISSUE TITLE
Unable to see results / @ account feature does not work for me

### ISSUE THREAD

**Issue by michellelkx** [neerajsinghsonu/Instagram-Data-Scraper#17]
Hi there,

Thanks for sharing this useful project!
After running WAMP server, and having it placed in my www root folder - I tried running it but
nothing is quite showing for the Hashword Graph (Please see the attached picture). 
Also for Accounts (@) it always give me an error of Error in Instagram profile link, wrong link.

Any idea how to resolve this? Am I supposed to be seeing some options?
Thanks!

![image](https://user-images.githubusercontent.com/2409796/38602555-adbb3fc4-3d9d-11e8-9984-3c7ca8301f6b.png)

**Comment by neerajsinghsonu** [comment]
Hi michellelkx,
Instagram has some new changes in their API and request URL. That's why the current application is not functioning properly. We are investigating and will patch new changes soon. The hashtag search working fine and issue is only in account information. For now we are releasing Hot Fix Patch to get basic account information....Please download new zip :)

**Comment by albero94** [comment]
Hello!

The user search is still not working right? I though you were not using API (of what I read in the description) so I don't really understand why the user search is not working now. 

I'm interested in that feature, I'm working on a group project with my class mates and we need to scrape some instagram data. If you have some information on how to fix that problem or make it work. We are willing to collaborate with it. 

As you have been working on this topic for a while, you can probably give me really valuable insights and feedback. I would really appreciate it.

Thanks!!! Alvaro.

**Comment by neerajsinghsonu** [comment]
Hi @albero94,

I am looking into the issue and trying to figure out some way to get the user's account details. Unfortunately, Instagram changed their API's bit, hence we couldn't be able to get any user account details without any valid session. But I think I have some good news for you and for others who wanted to get Instagram users account details by using this script.

The R&D is still in development mode and I got some success to get details, I will update this repo later when I will be able to explain things easier. 

**For now below are the key points:**

1. Instagram required us to send a valid session id to return the data.
2. The valid session id creates while user login.
3. You can login Instagram by using your Facebook login and can see the 'sessionid' and its value in browsers cookie.
4. You will be required to send this value whenever you will send request to get users or hastags data in json format by using the below urls.
Url to get data in JSON -
(A) - https://www.instagram.com/{USER-NAME}/?__a=1
(B) - https://www.instagram.com/explore/tags/{HASHTAG}/?__a=1

**_e.g. Below are the real world example:_**

- Fetch account details for user 'Martin'  - https://www.instagram.com/martin/?__a=1
- Fetch hashtags details for '#SweetCake' - https://www.instagram.com/explore/tags/sweetcake/?__a=1

You will get all result as in JSON format and you have to parse them to use your own business logic.

To get the next result like pagination you can use '?__a=1&max_id={max_id}', max_id is "end_cursor" value which is exsist in JSON response.

> "page_info": {
> "has_next_page": true,
> "end_cursor": "QVFBT0dtcFZUS3FDMXkzNHBwNzNEY1d0MUk5V1JjaWYtQ1RseEM3M3VSdklTMlZLZ2tCTlVucFd2OGVDZXA4U3gyUWY1TnoxOGduZmI3NGFlS1Bsa0lWNQ=="
> }

Kindly, let me know if it helps and also you can share your questions with me and we will crack secrets togeather :)

**_Tippy Tips:_** _You do not need to send session id to get #hashtag data, just open the link and you will get data._


Cheers!!
Neeraj Singh

**Comment by albero94** [comment]
Hi @neerajsinghsonu 

That's a lot of useful information! Thank you so much.

- I have reviewed a bit the information provided in JSON format in those URLs and it looks like it is exactly what I need. 

- The only thing missing would be loading the list of followers of the person which is not provided in that page. Do you know if there is JSON information in other URLs? The idea is go get this list of followers and analyze their profiles to identify which of them are fake/bought/not real followers.

    - I've tried same format in the followers page but it takes me to the profile URL. 
               https://www.instagram.com/martin/followers/?__a=1

Now that I know we can get the data we want this way, the following steps in our project is to prepare a simple app that is able to connect to instagram using one profile that we have created, grab the session ID and then download and parse the JSON data. I hope we do some progress in the following wee. I will keep you updated.

Thank you again for your information.
Best regards!
Alvaro.

**Comment by neerajsinghsonu** [comment]
Hello @michellelkx & @albero94 

Now you can search user account too.
