### ISSUE TITLE
It is still not working

### ISSUE THREAD

**Issue by gavyjatt** [neerajsinghsonu/Instagram-Data-Scraper#2]
I deployed this Application on my Local Server which is http://localhost:8089/instagram/

when i run it it gives the following error 

http://prntscr.com/fs1cme

also, i had renamed the dev.htaaccesss file to just .htaccess file, even then it does not do anything, Configured my Environment to use the Port instead of just sing the Localhost Env

**Comment by neerajsinghsonu** [comment]
Hi @gavyjatt  can you share browser net panel data, lets check what happening in ajax response and what we getting...

**Comment by gavyjatt** [comment]
Here is the One screen of Net Panle 

http://prntscr.com/fs1igx

another screen of extended Net panel of the fetch_data call 

http://prntscr.com/fs1j73

**Comment by gavyjatt** [comment]
if you need headers info and anything else, let me know

**Comment by neerajsinghsonu** [comment]
@gavyjatt  Ah!! Got it :), make sure `allow_url_fopen` is enable in WAMP/XAMP... please let me know if it works..?

**Comment by gavyjatt** [comment]
it is enabled in the xampp php.ini file

**Comment by neerajsinghsonu** [comment]
@gavyjatt  The error "Invalid or corrupt Instagram url:.... " comes while "file_get_contents" get null and it's because whether url link is invalid or `allow_url_fopen` is disable in PHP settings. Make sure you getting data by using `pre($source)` in Instagram class method `insta_connect`.

**Comment by neerajsinghsonu** [comment]
@gavyjatt  Please update Instagram class, I've just committed new code. I hope it will work for sure...

**Comment by gavyjatt** [comment]
That still did not worked

**Comment by gavyjatt** [comment]
i am trying to upload it for you to debug but somehow it is not working 
http://gr-group.in/_cfmprojects/instagram/index.php

**Comment by neerajsinghsonu** [comment]
Let's  discuss this tomorrow, we will make it work for sure . Now I am leaving from ofc..good night :)

**Comment by gavyjatt** [comment]
Are you still looking into the issue

**Comment by neerajsinghsonu** [comment]
@gavyjatt Hi, Just committed new code. Please check once and let me know if it's work..

**Comment by neerajsinghsonu** [comment]
@gavyjatt  Hi, I just check your live url link and found error on html body and it is "<b>Fatal error</b>:  Call to undefined function apache_get_modules() in <b>......nstagram\Helpers\Helper.php</b> on line <b>64</b><br />, Please make sure You have must be running PHP >= 4.3.2 and using Apache 2 handler API, or PHP >= 5.0 and Apache 1 or Apache 2 filter API.

**Comment by gavyjatt** [comment]
Hi, Looks like there is some progress as i see the message is different [ Getting data, please wait....]: but I see this error in console 

http://prntscr.com/fshkdq

**Comment by neerajsinghsonu** [comment]
@gavyjatt  Please check your php, apache error log first. Make sure you have enable PHP Error reporting

```php
 // Error reporting ON
error_reporting(E_ALL);
ini_set('display_errors', 1);
```

**Comment by gavyjatt** [comment]
between i am running on local, not on the server

**Comment by neerajsinghsonu** [comment]
@gavyjatt  Please check ajax response data and check any php error if you getting. The script won't work without cURl OR allow_url_fopen + openssl. make sure you have enable these settings in your wamp/xamp...

**Comment by gavyjatt** [comment]
not any php error, but it is syntax error if you see the error i sent

**Comment by neerajsinghsonu** [comment]
I just downloaded updated zip file and extract in my wamp/www folder, and for me everything working fine... unexpected token in js file means you have some PHP error in your html source. Please find the error  or share the Ajax Response Data...

**Comment by gavyjatt** [comment]
ok, i am running your exact code replica with 0 change and everything upto the fopen is on and openssl is installed

**Comment by neerajsinghsonu** [comment]
if you can share html source code here and ajax response too.. let me check if something is breaking from your end..

**Comment by gavyjatt** [comment]
Here is the HTML Code 

https://pastebin.com/bSa6dyb6

**Comment by neerajsinghsonu** [comment]
Send me the PHP, APACHE version details and share source of html & ajax response. I will check tomorrow and will try to fix error.  Good Night... :)

BTW I am using WAMP 3.0.6, PHP 5.6.25 & Apache 2.4.23

**Comment by gavyjatt** [comment]
i used the app.js instead on app.min.js and checked the code 

error seems to on this lie 

```
Instagram.prototype.initNow = function(link) {
    // cache main object
    var $this = this;
    // you said promise
    return $.post($this.sendRequestUrl, {
        iUrl: link
    }, function(data, textStatus, xhr) {
        $this.scriptContainer.html(data); **-- This one it points too**
        eval($this.scriptContainer.html());
```

**Comment by neerajsinghsonu** [comment]
Please pardon me, I have to leave for now from office. I will check issue tomorrow.. hope you don't mind.. Thank you :)

**Comment by gavyjatt** [comment]
No Worries, we will catch up later tomorrow

**Comment by gavyjatt** [comment]
This will help you debug 
http://prntscr.com/fsi0zo

Error found

**Comment by neerajsinghsonu** [comment]
Hi you can update helper and use CONTROLLER_PATH. Sorry for inconvenience its my nistake..:(

**Comment by neerajsinghsonu** [comment]
I will update repo Tomorrow sure..

**Comment by neerajsinghsonu** [comment]
Just updated Helper file by my mobile... Smart phons are really Smart :)

**Comment by gavyjatt** [comment]
That's working Dude, Awesome

**Comment by neerajsinghsonu** [comment]
Oh! Yeappi! Glad to Know..:) finally you got the luck ....
