### ISSUE TITLE
I can't install the script.

### ISSUE THREAD

**Issue by Fers4t** [neerajsinghsonu/Instagram-Data-Scraper#27]
I've read all issues about it but I can't install anyway. I'm not beginner but I can't understand what's the problem. Here is a video. Firstly I click search button and nothing happened. Secondly, I'm pushing enter and it's just refresh the page. Can anyone help me?

Here is a video: https://drive.google.com/open?id=1VHOV8D5bS-nKIR6gGJf-KNDLvyS620sV

**Comment by neerajsinghsonu** [comment]
Hi @Fers4t,

Thank you for explaining your issue on ISS (Instagram Super Scraper). As per your explanation, while you clicking the button nothing happening even after pressing the enter button the page is getting refreshed itself. So it could be the reason for you having any JavaScript related issues or browsers released issues. I request to share your browsers panel log, net panel status, and error if could see inside the inspect panel.

Also, I would like to share some important facts about the errors:

1. Check if you have curl enabled
2. Check if you have file_get_contents enable or curl
3. Check if any PHP error you are getting
4. Check if any network related issue you are getting

Kindly, share your latest information regarding error so I can check and help you to fix errors.

Regards,
Neeraj Singh

**Comment by Fers4t** [comment]
I'm running so many scripts on my hosts on same server. There is no JS issue for now. I'm using latest version of Chrome on Windows 7.

1. I'm using curl on my host, yes.
2. I don't know anything about that :/
3. There is no log file
4. I've no network issue

Thanks for answer by the way.

**Comment by neerajsinghsonu** [comment]
Okay, so you are using the script on the live host, if you do not mind can I know the public url; it will help me to figure out what is the issue. In case you do not have any public url so may I ask you to share a browser console panel screenshot.

You can also share your local url via using [NGROK](https://ngrok.com/), so I can check your existing local projects and can share some suggestions.

Thank you :)

**Comment by Fers4t** [comment]
"Show it, show it, show it
I'm stupid and I know it"

That was really stupid. I'm really upload a video instead of give a stupid url......
Here it is: http://bottagram.com/analiz

**Comment by neerajsinghsonu** [comment]
I got you ;)

Some of the important script and css file are net getting load on your host because they are missing or you have placed them in the wrong place. e.g. https://bottagram.com/analiz/public/jqcloud/dist/jqcloud.min.css is not getting load and js files as well. Please set the correct path or upload the required file on host server and you are good to go :) 

Screenshot:
<img width="1440" alt="screen shot 2019-02-02 at 3 56 39 pm" src="https://user-images.githubusercontent.com/1378886/52163142-02182500-2704-11e9-89ff-d64247120ca0.png">

Please do as advice and one thing "I love the Rap Songs" 🥇 :) :|

Cheers!!

**Comment by Fers4t** [comment]
Thaaaaanks! The problem is jQCloud folder. It should be jqcloud. I've renamed that and problem solved. Rap is our red line. Thanks again :)

**Comment by neerajsinghsonu** [comment]
You are very welcome :) have a good day.
