### ISSUE TITLE
would like know more about your solution

### ISSUE THREAD

**Issue by paulob93** [neerajsinghsonu/Instagram-Data-Scraper#33]
Hello,

My name is Paul and i am looking to build a similar project that what you created. I found your project very interesting and innovative and i would like to know more and share with you my project.

I am building and agency for influencers. If you would like to know more please contact on my mail - paul.bouletATclickanalyticDOTcom

Best,

Paul

**Comment by neerajsinghsonu** [comment]
Hello @paulob93 

Glad to hear about your start-up, and thanks for your comment. I applogies for late reply, I was badly stacked in daily schedule.

This project is totally free to use and anybody can take the source code. Unfortunately Paul I am not getting much time to explore more but I would be glad to help you whenever you got any any questions.

If you are building the commercial products then I would say start with the valid API and SDK which is validated and used by million of companies.

Instagram provides a platform to build the Instagram apps by registering the app and authorised the full application scope.

You can use their documents to understand the API flow and required inputs. You can do also for Twitter and Facebook. Every Big Social Platform provides you API and platform to build apps which can be connect from their core systems.

1. Choose your Social Platform
2. Get application approval
3. Build application API and echo system
4. Respect their policies
5. Setup the required infrastructure
6. Deploy the application
7. Check and Test

.. and that's it :)

Regards,
Neeraj Singh
