### ISSUE TITLE
File does not load

### ISSUE THREAD

**Issue by krautdawg** [neerajsinghsonu/Instagram-Data-Scraper#37]
Hello,

I am quite a n00b but I cannot get the php file to load in my browser. I unblocked the files but can't seem to get out of the loading screen of the death mode.

![grafik](https://user-images.githubusercontent.com/55399177/64968186-04e61580-d8a2-11e9-9e2a-7bf9d5e9a387.png)

Also from what I understand, it will be possible to look up stats for individual or even bulk of posts?
Thank you for building this and putting it online very generous.

Tim

**Comment by krautdawg** [comment]
Nevermind, I was able to load it up to repl.it and get it running. just needed a webserver :stuck_out_tongue_winking_eye:

**Comment by neerajsinghsonu** [comment]
@krautdawg 

ha ha ha.. :) Good to know you got that.

Thanks for your interest in this small utility script 👍
