### ISSUE TITLE
Adding business account email

### ISSUE THREAD

**Issue by mattnemus** [neerajsinghsonu/Instagram-Data-Scraper#38]
Hello,
it is possible to add an option where we can scrape business account email?

Regards,
Matt

**Comment by neerajsinghsonu** [comment]
Hi @mattnemus, 

Pardon but I didnt get you? What is the mean 'scrape business email'? Are we talking about to scraper email like from Gmail, Outlook etc. or we are talking about Instagram Business Email (well in this case you have to provide some more details to me to get it clearly).

We can scrape Gmail and Outlook via script like many web email apps do.

Awating for your response...

Regards,
Neeraj Singh

**Comment by mattnemus** [comment]
I'm sorry, I didn't say it very clearly. 
Instagram business accounts have shared their email, so people can get in touch more simple (https://prnt.sc/pberu8)
I would like to scrape these emails.

Thanks,
Matt

**Comment by neerajsinghsonu** [comment]
Hello @mattnemus,

Thanks for your information, I just want to keep it very simple that "anything which is visible for users' can be extracted from page/source. If business accouns has kept their contact/email address visible for all user then it could be extract.

Many Thanks,
Neeraj Singh

**Comment by mattnemus** [comment]
Hello,

You still don't understand. 
>"anything which is visible for users"

Business email is visible for every user, but we can't scrape it with your code, because we can only extract this kind of information (https://prnt.sc/pc5e5y)

Without adding code we can't extract other information that are visible.

Regards,
Matt

**Comment by neerajsinghsonu** [comment]
Hi @mattnemus, 

I got your point but what I was saying "Yes, we can extract the emails from accounts if it is visible for users". Yes, the code is not available yet to do this but, we can amend the script to get it done.

Just give me some business acount where I can see that email and let me check if I can do something for you :)

Cheers!
Neeraj Singh

**Comment by mattnemus** [comment]
Here is a business account you can try. https://www.instagram.com/danbilzerian/

Thank you very much.
Appreciate it!

Matt

**Comment by neerajsinghsonu** [comment]
Hi @mattnemus , 

Where I can find the email, I can only see the beautiful girls :D :) not any email address. Could you send me the excat location where I can get the emaill address. Or send me the screenshot where email is located.

**Comment by mattnemus** [comment]
Just realized, that email is only visible on mobile devices, not on desktop.

Tried to find in inspection tool, but can't find anything.

Matt
