### ISSUE TITLE
Instagram-Data-Scrapper issue

### ISSUE THREAD

**Issue by SanjeevKumar300** [neerajsinghsonu/Instagram-Data-Scraper#4]
Hi,
    I am able to successful run the program on Apache 2.4 on opening home page and importing links from Demo and then clicking GET_INFO I get the following errors even though links are correct

https://www.instagram.com/photowaali/.

 Error in Instagram profile link, wrong link

Regards
Sanjeev Kumar

**Comment by neerajsinghsonu** [comment]
Hi @SanjeevKumar300 ,

The script is working fine. The error you shared comes when any error occurs in json ajax response & its define inside JavaScript script. Please check ajax response in browser net panel inside XHR tab and share response if there is any error.

-Neeraj
