### ISSUE TITLE
[PAID] I need help to customize this script

### ISSUE THREAD

**Issue by luchomoya** [neerajsinghsonu/Instagram-Data-Scraper#40]
Hi,

First I would like to thank you for this awesome script.

I would like to make some customizations to this script but sadly my coding skills are limited. I would like to have a way to contact you Mr. Neeraj so I can offer you this project and we can work together. Could you give your email adress so I can contact you ? 

Have a nice day

**Comment by neerajsinghsonu** [comment]
Hi Mr. @chupacabras82,
Thanks for your offer but giving paid support is not my intention to build this script.
Regards,
Neeraj

**Comment by chupacabras82** [comment]
Thanks for your response.

Have a nice day
