### ISSUE TITLE
Loss of functionality?

### ISSUE THREAD

**Issue by JuDev09** [neerajsinghsonu/instagram-data-scraper#46]
In the Instagram account details section you no longer see the statistics of Likes, commets and views ... They will no longer be available?

**Comment by neerajsinghsonu** [comment]
Hello @JuDev09,

To get account details you have to paste your Instagram Session ID. For more information you can click on 'Set Session' Button beside 'Basic Details'. There are help links which will guide you to find your session id.

Hope it helps!

--
With Best
Neeraj Singh
