### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by Tefor** [neerajsinghsonu/instagram-data-scraper#49]
Hi, I'm using Wamp server. I downloaded the folder then put on /www/myfolder, when I request localhost/www/myfolder the page is blank. Should I do something else ? 

![Untitled](https://user-images.githubusercontent.com/26451058/109544625-a6542d80-7a7c-11eb-8a57-340e0c67b78b.png)

EDIT: I don't know if is related but I have 2 o 3 services running on my Wamp server

**Comment by neerajsinghsonu** [comment]
Hi @Tefor ,

Download the zip and extract it, it will create a folder name 'instagram-data-scraper-master' cut the folder and past inside /www folder. www folder is root folder for wamp and each files and folders will be accessible by http://localhost/your-file-name.extension or http://localhost/your-folder-name/

Hope that help!

**Comment by neerajsinghsonu** [comment]
I have just noticed that the page is showing the title, that means path is correct. May be the issue is something else. Plz show me the browser network panel and console screen shot.

**Comment by Tefor** [comment]
[
![aaaa](https://user-images.githubusercontent.com/26451058/109575001-c815da80-7aa5-11eb-9d57-93b1712c622e.png)
![asaa](https://user-images.githubusercontent.com/26451058/109575004-c9470780-7aa5-11eb-9138-15619b03c9b0.png)

](url)

**Comment by neerajsinghsonu** [comment]
Hi, all js and css are throwing 404, make sure all files are there -

public
logs
index.php
includes
config
README.md

**Comment by Tefor** [comment]
> Hi, all js and css are throwing 404, make sure all files are there -
> 
> public
> logs
> index.php
> includes
> config
> README.md

You were right, problem solved. I don't know why those files weren't there. Thanks for help
