### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mica418datasci** [neerajsinghsonu/Instagram-Data-Scraper#7]
i want to ask how to use this instagram-data-scraper. im having a hardtime figuring out how to install it or just use it by reading the readme a couple times. please help me

**Comment by neerajsinghsonu** [comment]
Hi Micaela Tullao,

Thank you for taking interest in ISS (Instagram Super Scraper). The ISS is a PHP application/script which runs on any apache + php, wamp, lamp and mamp. Make sure you have
installed any one of those services on your computer to run ISS properly. ISS will work like any other PHP application/script works with APACHE + PHP servers. 

Here are the links to help you to installed those service on your pc's.

1. [WAMP](http://www.wampserver.com/en/)
2. [LAMP](http://howtoubuntu.org/how-to-install-lamp-on-ubuntu)
3. [MAMP ](https://www.mamp.info/en/)

Install anyone of according to your OS (Operating System). Start Services and [Download the Zip file from Git Repository](https://github.com/neerajsinghsonu/Instagram-Data-Scraper/archive/master.zip). Extract the Zip file and move folder from extracted location to
WAMP/MAMP/LAMP www root. Start the localhost (open your browser and enter the local server address 'http://localhost or http://127.0.0.1 or check and confirm the address by your installed services). If the local server is running ok then you will see the folder name 'Instagram-Data-Scraper-master' in folder list, click on that and you will get http://localhost/Instagram-Data-Scraper-master address/url in your browser address bar. make sure you have configured all the required serveries which are mentioned on read me doc.  Here are the list of requirements:

**Requirement:**
Apache version => 2.4 PHP version =>5.* PHP allow_url_fopen & openssl or cURL enable Browser & Off-course internet Connection :)

**PHP Settings:**
A-) allow_url_fopen + openssl extension OR cURL enable

**Apache Settings:**
B-) Enable .htaccess (optional)

Hope now you have clear idea to run the application, If still you are getting any error or you have any question kindly let me know; I will surely reply to all your doubts as soon as possible. Till then enjoy the ISS and let me know your feedback please. 


Regards,
Neeraj Singh

**Comment by peter-michael** [comment]
Hi, I tried this also on my localhost and its just loading. I have all the requirements too, not sure what else I am missing. :(

**Comment by neerajsinghsonu** [comment]
Hi Peter Michael, 
The ISS is simple PHP scripts which works like any other PHP script. Place the code in your webserver root folder, connect internet, open localhost in any browser, navigate to project folder and access page. 

If still you are facing any problems kindly share error screen image and error.

Thanks
