### ISSUE TITLE
Instagram JSON Changed

### ISSUE THREAD

**Issue by absfarah** [neerajsinghsonu/Instagram-Data-Scraper#8]
I believe instagram has changed their JSON and unfortunately this doesn't work anymore.

Notice the graphql stuff:

`window._sharedData={"entry_data":{"ProfilePage":[{"graphql": {"hashtag": {"name": "testing", "is_top_media_only": false, "edge_hashtag_to_media": {"count": 37791,`

Do you plan to fix this? Would love to use this tool for research

**Comment by neerajsinghsonu** [comment]
Greetings!! well sure we will fix the ISS script if any changes made by Instagram. Time is certainly considerable and we will make it soon after the some test. Thanks to you to pointing the issue :) :)
