### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by simoneleopizzi** [neerajsinghsonu/Instagram-Data-Scraper#9]
I don't understand how I can install and run the application on apache server. I download all repo and I upload it on the server but when I visited the index.php I get a 403 error. Should I extract the archive? Thanks

**Comment by neerajsinghsonu** [comment]
Hi simoneleopizzi,

Please download the zip file from gtihub. Extract the zip content and move folder in your web root folder.
I am using wamp server so my web root path is 'D:\wamp\www\Instagram-Data-Scraper\' and I can open the project in browser by 'http://localhost/Instagram-Data-Scraper-master/'. It depends on your Web Server Software what you are using. I could help you better if you can share the exact error with me. 

Kindly follow the very simple step:

- Download the local server setup (wamp/mamp/lamp/xamp)
- Download the zip file from Github
- Extract the zip file and move the content in your web root folder

Now you can access the url by your web server url/folder-name
